# config.py

# File and directory names/paths relative to the project root
DEFAULT_VITAL_PRESET_FILENAME = "Default.vital"
DEFAULT_SERUM_PRESET_FILENAME = "output.fxp"
MAPPING_CSV_FILENAME = "SerumParameterMapping.csv"

# Define relative directories (these are relative to the project root)
PRESETS_DIR = "Presets"
MAPPINGS_DIR = "mappings"
OUTPUT_DIR = "output"

# MIDI configuration constants
MIDI_PITCH_REFERENCE = 69  # Middle A (A4)

# Default ADSR envelope values for fallback cases
DEFAULT_ADSR = {
    "attack": 0.01,
    "decay": 0.1,
    "sustain": 0.8,
    "release": 0.3
}

# Default waveform type for wavetable generation
DEFAULT_WAVEFORM = "saw"

# Harmonic scaling for different waveform types
HARMONIC_SCALING = {
    "sine": 10,
    "saw": 10,
    "square": 10,
    "triangle": 10,
    "pulse": 1  # Pulse wave typically doesn't use harmonics
}

# Mapping of MIDI CC numbers to Vital parameters
MIDI_TO_VITAL_MAP = {
    0: "bank_select",
    1: "mod_wheel",
    2: "macro2",
    3: "macro3",
    4: "macro4",
    5: "portamento_time",
    6: "data_entry",
    7: "osc_1_level",
    8: "osc_2_level",
    9: "osc_3_level",
    10: "osc_1_pan",
    11: "macro4",
    12: "effect_1_mix",
    13: "effect_2_mix",
    14: "lfo_1_rate",
    15: "lfo_2_rate",
    16: "lfo_3_rate",
    17: "lfo_4_rate",
    18: "osc_1_transpose",
    19: "osc_2_transpose",
    20: "macro1",
    21: "macro2",
    22: "macro3",
    23: "macro4",
    24: "osc_1_wavetable_position",
    25: "osc_2_wavetable_position",
    26: "osc_3_wavetable_position",
    27: "lfo_1_phase",
    28: "lfo_2_phase",
    29: "lfo_3_phase",
    30: "lfo_4_phase",
    31: "effect_1_depth",
    32: "phaser_rate",
    33: "phaser_depth",
    34: "phaser_feedback",
    35: "eq_low_freq",
    36: "eq_low_gain",
    37: "eq_mid_freq",
    38: "eq_mid_gain",
    39: "eq_high_freq",
    40: "eq_high_gain",
    41: "compressor_threshold",
    42: "compressor_ratio",
    43: "compressor_attack",
    44: "compressor_release",
    45: "distortion_drive",
    46: "distortion_mix",
    47: "delay_time",
    48: "delay_feedback",
    49: "delay_wet",
    50: "reverb_size",
    51: "reverb_decay",
    52: "reverb_dry_wet",
    53: "chorus_rate",
    54: "chorus_depth",
    55: "chorus_mix",
    56: "custom_wavetable_1",
    57: "custom_wavetable_2",
    58: "custom_wavetable_3",
    59: "custom_wavetable_4",
    60: "mod_matrix_1",
    61: "mod_matrix_2",
    62: "mod_matrix_3",
    63: "mod_matrix_4",
    64: "env_1_sustain",
    65: "portamento_on",
    66: "osc_1_wavetable_blend",
    67: "osc_2_wavetable_blend",
    68: "osc_3_wavetable_blend",
    69: "filter_1_blend",
    70: "filter_1_drive",
    71: "filter_1_resonance",
    72: "env_1_release",
    73: "env_1_attack",
    74: "filter_1_cutoff",
    75: "env_1_decay",
    76: "lfo_1_depth",
    77: "lfo_2_depth",
    78: "lfo_3_depth",
    79: "lfo_4_depth",
    80: "osc_2_level",
    81: "osc_3_level",
    82: "osc_1_phase",
    83: "osc_2_phase",
    84: "osc_3_phase",
    85: "filter_2_drive",
    86: "filter_2_blend",
    87: "filter_2_resonance",
    88: "effect_1_feedback",
    89: "effect_2_feedback",
    90: "effect_3_feedback",
    91: "reverb_dry_wet",
    92: "effect_2_rate",
    93: "chorus_dry_wet",
    94: "delay_time",
    95: "phaser_dry_wet",
    96: "data_increment",
    97: "data_decrement",
    98: "macro1",
    99: "macro2",
    100: "macro3",
    101: "macro4",
    102: "filter_2_cutoff",
    103: "filter_2_resonance",
    104: "filter_2_drive",
    105: "lfo_1_depth",
    106: "lfo_2_depth",
    107: "lfo_3_depth",
    108: "lfo_4_depth",
    109: "lfo_1_phase",
    110: "lfo_2_phase",
    111: "lfo_3_phase",
    112: "delay_feedback",
    113: "eq_low_gain",
    114: "eq_mid_gain",
    115: "eq_high_gain",
    116: "distortion_drive",
    117: "compressor_threshold",
    118: "compressor_ratio",
    119: "flanger_dry_wet",
    120: "all_sound_off",
    121: "reset_all_controllers",
    122: "local_control",
    123: "all_notes_off",
    124: "omni_off",
    125: "omni_on",
    126: "mono_on",
    127: "poly_on",
}
